name: bitmap
description: Bitmap is a fast and minimalistic lib that heelps you to manipulate image on Flutter apps.
version: 0.2.1
homepage: https://github.com/bluefireteam/bitmap
topics: [image, image-processing, ffi]

environment:
  sdk: ">=3.1.0"
  flutter: ">=3.13.9"

dependencies:
  equatable: ^2.0.8
  ffi: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.bitmap
        pluginClass: BitmapPlugin
      ios:
        pluginClass: BitmapPlugin
